### ISSUE TITLE
discord? or any other ways to contact you?

### ISSUE THREAD

**Issue by zaWarudo99** [blaueeiner/supbot#2]

**Comment by blaueeiner** [comment]
Yeah sure, but could you pls, only if possible describe, in general here what the matter is? 

Discord: blaueeiner#2601

**Comment by zaWarudo99** [comment]
Yea could you open a discord maybe?
So more get to know about your bot. And maybe help using the bot would be nice.

**Comment by blaueeiner** [comment]
Yes sure send me a friend request.

**Comment by zaWarudo99** [comment]
Nice , done 👌
